inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/bundle/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/MethodCallWithArgsParentheses:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: true
